### ISSUE TITLE
Playmodes

### ISSUE THREAD

**Issue by santi-playmodes** [emjibay/arts-et-medias#114]
Please answer the following questions. You can replace the example text.

All information is mandatory unless marked otherwise. Incomplete information prevent us from adding new content, ensure to help us out.

Ensure that the person you suggest is related to the world of media art which presented on *Arts & Médias*. We reserve the right to not add the people if their work is not in relation to our content.

## Name
Playmodes

## Description
Playmodes is an audiovisual research studio.

A hybrid team of engineers, musicians and designers who work with homw-made digital technologies, breathing life into original light and sound instruments. This digital luthierism has led them to apply their creativity to immersive installations, scenography or projection mapping, in a journey outside the square boundaries of traditional screens.

Their deep interest in the relationships between visual and auditory phenomena, leads Playmodes to create projects where sound and image are treated as a single matter. In most of their projects, the same streams of data generate both audio and visuals through homemade software, driving the audience into strong synaesthetic perceptions.

Passionate about art, design, maths, physics, code, cymatics and nature, they share all these passions by giving lectures and workshops in universities, schools or institutions.

In recent years Playmodes has developed projects for international art festivals (Barcelona, Houston, Prague, Lyon, Las Vegas, Orlando, Karlsruhe), for cultural and commercial projects (light design for the Copenhagen Opera, Installation for Facebook at Rio Olympics) or as guest speakers at international design conferences (FITC Amsterdam, IALD Albuquerque, OFFF Barcelona)

## Short Description
Playmodes is an audiovisual research studio.
A hybrid team of engineers, musicians and designers who work with home-made digital technologies, breathing life into original light and sound instruments. Their deep interest in the relationships between visual and auditory phenomena, leads them to create projects where sound and image are treated as a single matter.

## Website (optional)
https://www.playmodes.com/

## Profile Picture (optional)
![tubos_rgb](https://user-images.githubusercontent.com/17783713/119718109-76dc7380-be67-11eb-80b8-86047da3f725.png)

## Tags (optional)
media art, installation, audiovisual, creative coding, sound art, music composition, immersive

**Comment by jansensan** [comment]
Hello @santi-playmodes, thanks for your submission 🙏

Just to ensure I understand the request, you wish for us to update what is currently presented here: https://arts-et-medias.net/en/people/collectives/playmodes, correct? As soon as time permit, we will.

We also localize the content to French using [DeepL](https://arts-et-medias.net/en/people/collectives/playmodes). Let us know if that is ok with you.

Thanks again, we'll follow up ASAP.

**Comment by santi-playmodes** [comment]
Hey Matt, that's it! thank you!

actually, i introduced the playmodes descripitioin because i wanted to share this project wiith you:
https://www.playmodes.com/home/forms-string-quartet/

i'll go through thee submission github process once i have some free time,
i've been having some crazy days lately

thanks for your work!!!

**Comment by jansensan** [comment]
Profile updated:

EN: https://arts-et-medias.net/en/people/collectives/playmodes
FR: https://arts-et-medias.net/fr/personnes/collectifs/playmodes

Thanks for sharing the project it does look interesting!
